<h1>Pandas </h1>

Pandas DataFrame consists of three main components: the data, the index, and the columns.

<h3>importing libraries</h3>

In [1]:
import pandas as pd
import numpy as np

<h3>Creating dataframe</h3>

In [2]:
df=pd.DataFrame(data=np.arange(1,17).reshape(4,4),
                index=['1','2','3','4'],
                columns=['col1','col2','col3','col4'])

print(pd.DataFrame(data=np.arange(1,17).reshape(4,4),index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4']))
print("\n")
print(pd.DataFrame(data=np.arange(1,17).reshape(4,4)))

      col1  col2  col3  col4
row1     1     2     3     4
row2     5     6     7     8
row3     9    10    11    12
row4    13    14    15    16


    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16


<h3>head() </h3>

In [3]:
df.head(2)

col1  col2  col3  col4
1     1     2     3     4
2     5     6     7     8

<h3>Accessing particular column</h3>

In [4]:
df['col1'] 

1     1
2     5
3     9
4    13
Name: col1, dtype: int32

In [5]:
df

col1  col2  col3  col4
1     1     2     3     4
2     5     6     7     8
3     9    10    11    12
4    13    14    15    16

<h3>indexing</h3>

In [6]:
df.iloc[2:,2:]

col3  col4
3    11    12
4    15    16

<h3>value counts</h3>

In [7]:
#Value_counts: Return how many times each values present in particular column
df['col1'].value_counts() 

9     1
1     1
5     1
13    1
Name: col1, dtype: int64

In [8]:
df.value_counts()

col1  col2  col3  col4
1     2     3     4       1
5     6     7     8       1
9     10    11    12      1
13    14    15    16      1
dtype: int64

<h3>describe()</h3>

In [9]:
df.describe()

col1       col2       col3       col4
count   4.000000   4.000000   4.000000   4.000000
mean    7.000000   8.000000   9.000000  10.000000
std     5.163978   5.163978   5.163978   5.163978
min     1.000000   2.000000   3.000000   4.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     7.000000   8.000000   9.000000  10.000000
75%    10.000000  11.000000  12.000000  13.000000
max    13.000000  14.000000  15.000000  16.000000

<h3>imprting csv file </h3>

In [10]:
dataset = pd.read_csv('Datasets\mbgm_lbs.csv')
dataset

team_id    rank    score        date       lb  submissions
0           1.0  1402.0  0.54841  2017-07-04  private          1.0
1           1.0  1442.0  0.54841  2017-07-05  private          0.0
2           1.0  1466.0  0.54841  2017-07-06  private          0.0
3           1.0  1492.0  0.54841  2017-07-07  private          0.0
4           1.0  1515.0  0.54841  2017-07-08  private          0.0
...         ...     ...      ...         ...      ...          ...
215205      NaN     NaN -0.00039  2017-07-07   public          NaN
215206      NaN     NaN -0.00039  2017-07-08   public          NaN
215207      NaN     NaN -0.00039  2017-07-09   public          NaN
215208      NaN     NaN -0.00039  2017-07-10   public          NaN
215209      NaN     NaN -0.00039  2017-07-11   public          NaN

[215210 rows x 6 columns]

In [11]:
dataset.shape 

(215210, 6)

In [12]:
dataset.describe()

team_id           rank         score    submissions
count  215124.000000  215124.000000  2.152100e+05  215124.000000
mean     1925.769068    1498.665830 -5.399672e+92       0.731699
std      1115.288198     984.525605  1.477749e+95       1.611397
min         1.000000       1.000000 -4.724287e+97       0.000000
25%       978.000000     663.000000  5.404500e-01       0.000000
50%      1926.000000    1380.000000  5.490400e-01       0.000000
75%      2861.000000    2231.000000  5.547100e-01       0.000000
max      3927.000000    3927.000000  6.304500e-01      30.000000

In [13]:
dataset['team_id'].value_counts()

635.0     84
19.0      84
392.0     84
2586.0    84
197.0     84
          ..
2852.0     2
2137.0     2
3623.0     2
3060.0     2
3654.0     2
Name: team_id, Length: 3927, dtype: int64

In [14]:
dataset['team_id'].unique()

array([1.000e+00, 2.000e+00, 3.000e+00, ..., 3.926e+03, 3.927e+03,
             nan])

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215210 entries, 0 to 215209
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   team_id      215124 non-null  float64
 1   rank         215124 non-null  float64
 2   score        215210 non-null  float64
 3   date         215210 non-null  object 
 4   lb           215210 non-null  object 
 5   submissions  215124 non-null  float64
dtypes: float64(4), object(2)
memory usage: 9.9+ MB


In [16]:
dataset['submissions'].value_counts()

0.0     169222
5.0      19354
1.0       9519
2.0       6741
3.0       5401
4.0       4504
10.0       154
7.0         63
6.0         54
8.0         44
9.0         42
15.0         8
11.0         6
12.0         4
13.0         4
18.0         1
24.0         1
30.0         1
23.0         1
Name: submissions, dtype: int64

In [17]:
dataset['team_id'].value_counts()

635.0     84
19.0      84
392.0     84
2586.0    84
197.0     84
          ..
2852.0     2
2137.0     2
3623.0     2
3060.0     2
3654.0     2
Name: team_id, Length: 3927, dtype: int64

In [18]:
#Select all values where value of submission is greater than 23
dataset[dataset['submissions']>23] 

team_id  rank    score        date      lb  submissions
133974    958.0   4.0  0.59676  2017-07-10  public         24.0
133988    959.0   4.0  0.57218  2017-06-14  public         30.0

<h3>Creating dataframe from list </h3>

In [19]:
list_data = list([[1,2,3,np.nan],[4,5,np.nan,np.nan],[6,np.nan,np.nan,np.nan]])
list_data

[[1, 2, 3, nan], [4, 5, nan, nan], [6, nan, nan, nan]]

In [20]:
df = pd.DataFrame(list_data)
df

0    1    2   3
0  1  2.0  3.0 NaN
1  4  5.0  NaN NaN
2  6  NaN  NaN NaN

In [21]:
df.isna()

0      1      2     3
0  False  False  False  True
1  False  False   True  True
2  False   True   True  True

<h3>dropna</h3>

In [22]:
df.dropna(axis=1) #Drop column where we have null value

0
0  1
1  4
2  6

In [23]:
df

0    1    2   3
0  1  2.0  3.0 NaN
1  4  5.0  NaN NaN
2  6  NaN  NaN NaN

<h3>fillna</h3>

In [24]:
df.fillna(1)

0    1    2    3
0  1  2.0  3.0  1.0
1  4  5.0  1.0  1.0
2  6  1.0  1.0  1.0

<h3>loc: used for row</h3>

In [25]:
df.loc[0] #Used for selecting row

0    1.0
1    2.0
2    3.0
3    NaN
Name: 0, dtype: float64

<h3>iloc: used for both row and column</h3>

In [26]:
df.iloc[1:,2:] #used for both row and column

2   3
1 NaN NaN
2 NaN NaN

In [27]:
df.iloc[:,:]

0    1    2   3
0  1  2.0  3.0 NaN
1  4  5.0  NaN NaN
2  6  NaN  NaN NaN

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
print(df.iloc[0:1,0:])
type(df.iloc[0:1,0:])

   0    1    2   3
0  1  2.0  3.0 NaN


pandas.core.frame.DataFrame

In [30]:
print(df.iloc[0:1,0])
type(df.iloc[0:1,0])

0    1
Name: 0, dtype: int64


pandas.core.series.Series

<h3>Dataframe to array</h3>

In [31]:
#Converting dataframe to array 
df.iloc[:,:].values

array([[ 1.,  2.,  3., nan],
       [ 4.,  5., nan, nan],
       [ 6., nan, nan, nan]])

<h3>isnull</h3>

In [32]:
df.isnull()

0      1      2     3
0  False  False  False  True
1  False  False   True  True
2  False   True   True  True

<h3>Return total number of null values ,column wise</h3>

In [33]:
#Col 0 contain 0 null value
df.isnull().sum() 

0    0
1    1
2    2
3    3
dtype: int64

<h3>Return unique values(which are not repaeating</h3>

In [34]:
df[0].unique() 

array([1, 4, 6], dtype=int64)

In [35]:
df

0    1    2   3
0  1  2.0  3.0 NaN
1  4  5.0  NaN NaN
2  6  NaN  NaN NaN

In [36]:
df[[0,1]] #Return 0 and 1 column

0    1
0  1  2.0
1  4  5.0
2  6  NaN

<h3>Url to dataframe</h3>

In [38]:
df = pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item",sep='\t')
df

item_code                                          item_name  \
0         AA0                               All items - old base   
1        AA0R  Purchasing power of the consumer dollar - old ...   
2         SA0                                          All items   
3        SA0E                                             Energy   
4       SA0L1                                All items less food   
..        ...                                                ...   
394   SS68023   Tax return preparation and other accounting fees   
395   SSEA011                                  College textbooks   
396  SSFV031A           Food at elementary and secondary schools   
397   SSGE013                                 Infants' equipment   
398   SSHJ031                                 Infants' furniture   

     display_level selectable  sort_sequence  
0                0          T              2  
1                0          T            399  
2                0          T              1  
3                1          T            374  
4                1          T            358  
..             ...        ...            ...  
394              4          T            352  
395              3          T            314  
396              3          T            122  
397              3          T            355  
398              3          T            165  

[399 rows x 5 columns]

<h3>JSON to dataframe</h3>

In [39]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(Data)
df

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [40]:
df

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [41]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'