<h1>Chapter 2</h1>

In [1]:
num=[1,2,3,4,5]
x=num
x[1]=6
print(num)
print(x)

[1, 6, 3, 4, 5]
[1, 6, 3, 4, 5]


In [4]:
num=[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
print(num)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [19]:
print(num[0][2:])

[3, 4, 5]


<h1>Chapter 3 : Functions</h1>

In [24]:
fam = [1.73, 1.68, 1.71, 1.89]
max(fam)

1.89

In [25]:
round(12.3243,2)

12.32

In [27]:
round(12.3248,3)

12.325

In [28]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [29]:
fam = [1, 1, 1, 1,2,2,3,4,54,65]
fam.count(1)

4

In [30]:
fam.index(2)

4

<h1>Chapter 4 : Numpy </h1>

In [32]:
arr1 = [1,2,3,4,5]
arr2 = [4,5,6,7,8]
arr1/arr2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [33]:
import numpy as np
arr1=np.array(arr1)
arr2=np.array(arr2)
print(arr1+arr2)

[ 5  7  9 11 13]


In [34]:
print(np.array([10,12.54,'ali',True]))

['10' '12.54' 'ali' 'True']


In [37]:
age = [0,1,2,3,4,54,1,12,32,53,56,76,18,19,12,21,43,54,67]
for i in age:
    if i<18:
        print(i)

0
1
2
3
4
1
12
12


In [39]:
age = [0,1,2,3,4,54,1,12,32,53,56,76,18,19,12,21,43,54,67]
age = np.array(age)
print(age<18)
print(age[age<18])

[ True  True  True  True  True False  True  True False False False False
 False False  True False False False False]
[ 0  1  2  3  4  1 12 12]


In [40]:
age_2d=[
    [0,1,2,3,4,54,1,12,32,53,56,76,18,19,12,21,43,54,67],
    [0,1,2,3,4,54,1,12,32,53,56,76,18,19,12,21,43,54,67],
    [0,1,2,3,4,54,1,12,32,53,56,76,18,19,12,21,43,54,67]
]

age_2d=np.array(age_2d)
print(type(age_2d))

<class 'numpy.ndarray'>


In [41]:
age_2d[0][0]

0

In [45]:
age_2d[2,2]

2

In [48]:
age_2d[0:,2]

array([2, 2, 2])

In [50]:
age_2d[0:,-2:]

array([[54, 67],
       [54, 67],
       [54, 67]])

In [51]:
np.mean(age_2d[0:,3])

3.0

In [52]:
np.median(age_2d[0:,3])

3.0

In [53]:
np.std(age_2d[0:,3])

0.0

In [55]:
np.random.normal(1.76,0.20,10)

array([1.9056936 , 1.74006349, 1.88352632, 1.71587366, 2.00653281,
       1.71553218, 1.9791554 , 1.78066483, 1.47839048, 1.580017  ])