<h1>Python For data science</h1>

In [1]:
print("Heloo")

Heloo


<h2>Numpy tutorial</h2>

<h4>Importing numpy</h4>

In [2]:
import numpy as np

In [8]:
np_array = np.array([1,2,3,4,5])
print(type(np_array))

arr= [1,2,3,4,5]
print(type(arr))

<class 'numpy.ndarray'>
<class 'list'>


<h4>np.arange function</h4>

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [15]:
mt_np_array = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
print(np.array(mt_np_array))

print(type(mt_np_array))

print(type(np.array(mt_np_array)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
<class 'numpy.ndarray'>


In [20]:
mt_np_array = [
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
mt_np_array  = np.array(mt_np_array)
print(mt_np_array.shape)

(4, 3)


<h4>indexing</h4>

In [26]:
one_d_np_array =np.arange(1,11) 
print(one_d_np_array)
print(one_d_np_array[0:4])  #Print values from index 0-3

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4]


In [34]:
two_d_np_array = [
    [1,2,3],
    [7,8,9]
]
two_d_np_array  = np.array(two_d_np_array )
print(two_d_np_array[0:2,1:]) #[start index of row : end index of row , start index of col: end index of col]

[[2 3]
 [8 9]]


In [35]:
mt_np_array = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
mt_np_array  = np.array(mt_np_array)

print(mt_np_array[1:3,1:3])

[[5 6]
 [8 9]]


<h4>Arithmetic operators</h4>

In [36]:
#Add oeprator with list
arr1 = [1,2,3,4,5]
arr2 = [1,2,3,4,5]

print(arr1+arr2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [39]:
#Numpy arithmetics
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


<h4>Reshape</h4>

In [42]:
#Numpy reshape
arr = np.array([1,2,3,4,5])
print(arr.shape)
reshaped_arr = arr.reshape([1,5])
print(reshaped_arr.shape)

(5,)
(1, 5)


In [46]:
print(np.ones([3,3]))
print("\n")
print(np.ones([3,3],dtype=int))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[1 1 1]
 [1 1 1]
 [1 1 1]]


<h4>Random numbers</h4>

In [50]:
np.random.rand(3,3)

array([[0.22688065, 0.55942231, 0.16320439],
       [0.17327101, 0.65399204, 0.65267042],
       [0.511681  , 0.96056196, 0.66961109]])

In [53]:
np.random.randn(3,3)

array([[-0.50416579, -0.14650381, -0.85561006],
       [ 0.28507325,  0.65647792,  0.01163132],
       [ 1.78276474,  0.7839807 ,  2.64719625]])

In [57]:
np.random.randint(1,10,2)

array([5, 1])

In [59]:
np.random.random_sample(4)

array([0.5521462 , 0.3377772 , 0.2858522 , 0.85005802])

<h4>linespace</h4>

In [66]:
# print 50 equally spaced points between 1 and 10
np.linspace(1,10,50) 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

<h4>copy and assigning</h4>

In [74]:
#Assiging is actually passed by reference
arr = np.arange(0,10)
arr[3:]=10
print("arr Before copying\n")
print(arr)

arr1 = arr
arr1[3:]=50

print("arr1\n")
print(arr1)
print("arr after copying\n")
print(arr)

arr Before copying

[ 0  1  2 10 10 10 10 10 10 10]
arr1

[ 0  1  2 50 50 50 50 50 50 50]
arr after copying

[ 0  1  2 50 50 50 50 50 50 50]


In [75]:
#Copy is actually passed by value
arr = np.arange(0,10)
arr[3:]=10
print("arr Before copying\n")
print(arr)

arr1 = arr.copy()
arr1[3:]=50

print("arr1\n")
print(arr1)
print("arr after copying\n")
print(arr)

arr Before copying

[ 0  1  2 10 10 10 10 10 10 10]
arr1

[ 0  1  2 50 50 50 50 50 50 50]
arr after copying

[ 0  1  2 10 10 10 10 10 10 10]


<h4>Conditioinal</h4>

In [81]:
arr = np.arange(0,10)
print(arr)
print(arr<5)
print(arr[arr<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
